# Generated by Django 3.2.9 on 2022-01-11 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AssignmentTitle', models.CharField(max_length=250)),
                ('AssignmentDescription', models.TextField()),
                ('AssignmentLink', models.CharField(max_length=250)),
                ('AssignmentAttachment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('BatchId', models.AutoField(primary_key=True, serialize=False)),
                ('BatchName', models.CharField(default='Name Me', max_length=250)),
                ('BatchStartDate', models.DateField()),
                ('BatchEndDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('SessionId', models.AutoField(primary_key=True, serialize=False)),
                ('SessionStartDate', models.DateTimeField()),
                ('SessionEndDate', models.DateTimeField()),
                ('sessioncoordinateuser', models.CharField(max_length=250, null=True)),
                ('sessioninstructor', models.CharField(max_length=250, null=True)),
                ('noofparticipants', models.IntegerField(default=1)),
                ('sessiontitle', models.CharField(default='', max_length=250, null=True)),
                ('sessionhash', models.CharField(default='', max_length=250, null=True)),
                ('sessionfile', models.CharField(max_length=500, null=True)),
                ('BatchId', models.ForeignKey(db_column='BatchId', on_delete=django.db.models.deletion.CASCADE, to='portal.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusId', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=250)),
                ('StudentContact', models.CharField(max_length=250, null=True)),
                ('StudentEmail', models.CharField(max_length=250)),
                ('StudentGender', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('WorkId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('PercentFinish', models.CharField(max_length=250)),
                ('AssignmentName', models.CharField(max_length=250)),
                ('AssignmentProperty', models.CharField(max_length=250)),
                ('AssignmentValue', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('StudentAttendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('JoinTime', models.DateTimeField()),
                ('LeaveTime', models.DateTimeField()),
                ('Duration', models.CharField(max_length=20)),
                ('SessionId', models.ForeignKey(db_column='SessionId', on_delete=django.db.models.deletion.CASCADE, to='portal.session')),
                ('StudentId', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('ModuleId', models.AutoField(primary_key=True, serialize=False)),
                ('ModuleName', models.CharField(default='Dummy Module', max_length=1000)),
                ('ModuleType', models.CharField(max_length=250)),
                ('LiveClasses', models.IntegerField(null=True)),
                ('SelfLearning', models.IntegerField(null=True)),
                ('SelfLearningLink', models.CharField(max_length=250, null=True)),
                ('WorkLink', models.CharField(max_length=250, null=True)),
                ('CourseId', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
                ('ParentModuleId', models.ForeignKey(db_column='ParentModuleId', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.coursemodule')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('CourseCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
                ('CourseId', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
            ],
        ),
        migrations.CreateModel(
            name='BatchStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Status', models.TextField(max_length=30)),
                ('BatchId', models.ForeignKey(db_column='BatchId', on_delete=django.db.models.deletion.CASCADE, to='portal.batch')),
                ('StudentId', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
                ('UserId', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('BatchId', models.ForeignKey(db_column='BatchId', on_delete=django.db.models.deletion.CASCADE, to='portal.batch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('BatchAssignmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AssignmentId', models.ForeignKey(db_column='AssignmentId', on_delete=django.db.models.deletion.CASCADE, to='portal.assignment')),
                ('BatchId', models.ForeignKey(db_column='BatchId', on_delete=django.db.models.deletion.CASCADE, to='portal.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='CategoryId',
            field=models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.CASCADE, to='portal.category'),
        ),
        migrations.AddField(
            model_name='batch',
            name='StatusId',
            field=models.ForeignKey(db_column='StatusId', on_delete=django.db.models.deletion.CASCADE, to='portal.status'),
        ),
    ]
