# Generated by Django 3.2.9 on 2022-01-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='BatchId',
            field=models.ForeignKey(db_column='BatchId', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.batch'),
        ),
    ]
