# Generated by Django 3.2.9 on 2022-02-14 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_session_batchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotes',
            fields=[
                ('NotesId', models.AutoField(primary_key=True, serialize=False)),
                ('NotesDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('NotesDescription', models.TextField()),
                ('NotesEditor', models.CharField(max_length=250)),
                ('StudentId', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
    ]
