# Generated by Django 2.1 on 2022-04-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_studentnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentapidata', models.CharField(max_length=250, null=True)),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Email', models.CharField(max_length=250, null=True)),
                ('assignments', models.CharField(max_length=250, null=True)),
                ('duedate', models.DateField(null=True)),
                ('submiteddate', models.CharField(max_length=250, null=True)),
                ('unsubmiteddate', models.CharField(max_length=250, null=True)),
                ('returndate', models.CharField(max_length=250, null=True)),
                ('reassingndate', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(max_length=250, null=True)),
                ('feedback', models.CharField(max_length=300, null=True)),
                ('points', models.CharField(max_length=5, null=True)),
                ('assingment_delay', models.CharField(max_length=6, null=True)),
                ('assingment_check_delay', models.CharField(max_length=6, null=True)),
                ('batchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Batch')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Student')),
            ],
        ),
    ]
