# Generated by Django 2.1 on 2022-05-10 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_assignment_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_class_detail',
            fields=[
                ('Teacher_class_sequence', models.AutoField(primary_key=True, serialize=False)),
                ('Teacher_name', models.CharField(max_length=250, null=True)),
                ('Teacherintime', models.DateTimeField(null=True)),
                ('Teacherouttime', models.DateTimeField(null=True)),
                ('Teacheremail', models.CharField(max_length=250, null=True)),
                ('teacher_duration', models.CharField(max_length=20, null=True)),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
