# Generated by Django 2.1 on 2022-05-13 06:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_teacher_class_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketcategory',
            fields=[
                ('ticketcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('ticketcategoryname', models.CharField(max_length=100)),
                ('ticketcategorydesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('ticketdescription', models.TextField()),
                ('ticketcreatedate', models.DateTimeField(default=datetime.datetime.now)),
                ('lastmodifieddate', models.DateTimeField(default=datetime.datetime.now)),
                ('stdname', models.CharField(db_column='stdname', max_length=100)),
                ('stdemail', models.CharField(db_column='stdemail', max_length=100)),
                ('assignedtouser', models.ForeignKey(db_column='assignedtouser', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, to='portal.Student')),
                ('ticketcategory', models.ForeignKey(db_column='ticketcategory', on_delete=django.db.models.deletion.CASCADE, to='portal.ticketcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ticketstatus',
            fields=[
                ('ticketstatusid', models.AutoField(primary_key=True, serialize=False)),
                ('ticketstatusname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ticketsubcategory',
            fields=[
                ('ticketsubcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('ticketsubcategoryname', models.CharField(max_length=100)),
                ('ticketsubcategorydesc', models.TextField()),
                ('ticketcategoryid', models.ForeignKey(db_column='ticketcategoryid', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.ticketcategory')),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticketstatus',
            field=models.ForeignKey(db_column='ticketstatus', default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.ticketstatus'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticketsubcategory',
            field=models.ForeignKey(db_column='ticketsubcategory', on_delete=django.db.models.deletion.CASCADE, to='portal.ticketsubcategory'),
        ),
    ]
