# Generated by Django 3.2.8 on 2022-05-26 08:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_auto_20220513_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='celerytask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytaskid', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Complete'), ('ERR', 'Error')], default='PEN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='meetingcategory',
            fields=[
                ('meetingCategoryId', models.AutoField(db_column='meetingCategoryId', primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='mycelerytask',
            fields=[
                ('mytaskId', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Createmeetings',
            fields=[
                ('meetingid', models.AutoField(primary_key=True, serialize=False)),
                ('startdatetime', models.DateTimeField(db_column='startdatetime', default=datetime.datetime.now)),
                ('enddatetime', models.DateTimeField(db_column='enddatetime', default=datetime.datetime.now)),
                ('locations', models.CharField(db_column='locations', max_length=100)),
                ('meetingdetail', models.CharField(db_column='meetingdetail', max_length=100)),
                ('addchannels', models.ForeignKey(db_column='addchannels', on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
                ('attendee', models.ForeignKey(db_column='attendee', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donotrepeat', models.ForeignKey(db_column='donotrepeat', on_delete=django.db.models.deletion.CASCADE, to='portal.meetingcategory')),
            ],
        ),
    ]
