# Generated by Django 3.2.8 on 2022-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_celerytask_createmeetings_meetingcategory_mycelerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='BatchEmail',
            field=models.CharField(default='BatchEmail', max_length=250),
        ),
    ]
