# Generated by Django 3.2.8 on 2022-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_batch_batchemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='batchmeeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Batchid', models.IntegerField()),
            ],
        ),
    ]
